# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Move to app folder
      run: cd app

    - name: Create docker image
      run: docker build -t calc_app_img .

  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Remove old docker container
      run: docker container rm calc_app --force || true

    - name: Run docker container
      run: docker run --rm --name calc_app -p 8080:8080 calc_app_img