name: Build, test and deploy service

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Create test app docker image
      run: docker build -t calc_app_test_img app/.
    - name: Create pytest docker image
      run: docker build -t calc_app_pytest_img test/.

  run-test-app:
    needs: build-test
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Create test network
      run: docker network create calc-test-net || true
    - name: Run test app docker container
      run: docker run -d --name calc_test_app --network calc-test-net calc_app_test_img

  test:
    needs: run-test-app
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run pytest docker container
      run: docker run --rm --name calc_app_pytest --network calc-test-net calc_app_pytest_img

  stop-test-app:
    needs: test
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Remove old test app docker container
      run: docker container rm calc_test_app --force
    - name: Create test network
      run: docker network rm calc-test-net

#  build:
#    needs: test
#    runs-on: self-hosted
#    steps:
#    - uses: actions/checkout@v2
#     - name: Create app docker image
#       run: docker build -t calc_app_img app/.

  deploy:
    needs: test
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Rename test app docker image
      run: |
        docker tag calc_app_test_img calc_app_img
        docker rmi calc_app_test_img
    - name: Remove old app docker container
      run: docker container rm calc_app --force || true
    - name: Run app docker container
      run: docker run --rm -d --name calc_app -p 8080:8080 calc_app_img