name: Build, test and deploy service

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Create test app docker image
      run: docker build -t calc_app_test_img app/.
    - name: Create pytest docker image
      run: docker build -t calc_app_pytest_img test/.

  test:
    needs: build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Create test network
      run: docker network create --driver bridge calc-test-net || true
    - name: Run test app and pytest docker image
      run: |
        docker container rm calc_test_app --force || true
        docker run --rm -d --name calc_test_mongo --network calc-test-net mongo
        docker run --rm -d --env TEST_CALC_APP='true' --name calc_test_app --network calc-test-net calc_app_test_img
        docker run --rm --name calc_app_pytest --network calc-test-net calc_app_pytest_img
    - name: Remove test network and old test app docker container
      run: |
        docker container rm --force calc_test_app
        docker container rm --force calc_test_mongo
        docker network rm calc-test-net

  deploy:
    needs: test
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Rename test app docker image
      run: |
        docker tag calc_app_test_img calc_app_img
        docker rmi calc_app_test_img
    - name: Run app docker container
      run: |
        docker container rm calc_app --force || true
        docker run --rm -d --name calc_app --network host -p 8080:8080 calc_app_img